### PR TITLE
don't recurse into kwargs-munging code (resolves #48)

### LINKED ISSUE #48: Overdubbing kwargs methods
It's currently _possible_ to do this manually:
```julia
@isprimitive (::getfield(Base, Symbol("#kw##mapreduce")))(::Any...) where {__CONTEXT__ <: TraceCtx}
```
But it would be much nicer if it were built in:
```julia
@isprimitive mapreduce(::Any...; kwargs...) where {__CONTEXT__ <: TraceCtx}
```
because the generated `#kw#` methods and the namedtuple-munging code with which they start are a Julia implementation detail that isn't visible during ordinary method overloading.

Basically, I want to see this call tower:
```julia
sum([0.52695 0.88639; 1.0 1.0]; dims = 1)
  Base._sum([0.52695 0.88639; 1.0 1.0], 1)
```
and not this one:
```julia
getfield(Base, Symbol("#kw##sum"))()((dims = 1,), sum, [0.52695 0.88639; 1.0 1.0])
  haskey((dims = 1,), :dims)
   isdefined((dims = 1,), :dims)
  getindex((dims = 1,), :dims)
   getfield((dims = 1,), :dims)
  Core.apply_type(NamedTuple, (:dims,))
  Base.structdiff((dims = 1,), NamedTuple{(:dims,),T} where T<:Tuple)
   Core.apply_type(NamedTuple, (), Tuple{})
   NamedTuple{(),Tuple{}}((),)
    Core.apply_type(NamedTuple, (), Tuple{})
  pairs(NamedTuple(),)
   keys(NamedTuple(),)
   Base.Iterators.Pairs(NamedTuple(), ())
    eltype(Tuple{},)
    eltype(NamedTuple{(),Tuple{}},)
     eltype(Tuple{},)
    Core.apply_type(Base.Iterators.Pairs, Union{}, Union{}, Tuple{}, NamedTuple{(),Tuple{}})
    fieldtype(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, :data)
    convert(NamedTuple{(),Tuple{}}, NamedTuple())
    fieldtype(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, :itr)
    convert(Tuple{}, ())
  isempty(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}(),)
   Base.isdone(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}(),)
    getproperty(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}(), :itr)
     getfield(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}(), :itr)
    Core._apply(Base.isdone, ((),), ())
     Base.isdone((),)
   !==(missing, missing)
    ===(missing, missing)
    !(true,)
     not_int(true,)
   iterate(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}(),)
    getproperty(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}(), :itr)
     getfield(Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}(), :itr)
    Core._apply(iterate, ((),), ())
     iterate((),)
      iterate((), 1)
       length((),)
        nfields((),)
       <(0, 1)
        slt_int(0, 1)
    ===(nothing, nothing)
   ===(nothing, nothing)
  Base.#sum#542(1, sum, [0.52695 0.88639; 1.0 1.0])
   Base._sum([0.52695 0.88639; 1.0 1.0], 1)
```

### PR DESCRIPTION
**Pull request by jrevels**
cc @jekbradbury does this resolve your issue?

### CODE REVIEW

**Comment by jrevels** [comment]
Hmm. The tests are failing because we need to overdub the kwargs machinery for nested tagged execution to be correct.

We have a couple options here: 

1) If tagging is disabled, don't overdub the kwargs machinery. If tagging is enabled, do overdub the kwargs machinery
2) Always overdub kwargs machinery (i.e. behavior on `master`)
3) Try to do some tagging transforms at the IR level for the `iskwfunc` functions that allows tagging to work without needing to actually overdub into the machinery

3 would give us the most desirable behavior if we can do it correctly, but I'm not sure how that implementation would turn out. I'll take a crack at it and report back.

**Comment by jrevels** [comment]
Okay, fixed - that was actually way easier than I thought.

**Comment by jekbradbury** [comment]
This avoids recursing into kwargs-munging code inside kwfuncs themselves, but there's still the NamedTuple-constructing code that gets inserted during lowering at the location of kwargs calls:

```julia
julia> @overdub TraceCtx(metadata=Ref(0)) trkwtest(x, _y=y, _z=z)
┌ Debug: original CodeInfo
│   args = (getfield(Main, Symbol("##9#10")),)
│   reflection.code_info =
│    CodeInfo(
│    79 1 ─ %1 = (:_y, :_z)::Any
│       │   %2 = Core.apply_type(Core.NamedTuple, %1)::Any
│       │   %3 = Core.tuple(Main.y, Main.z)::Any
│       │   %4 = %2(%3)::Any
│       │   %5 = Core.kwfunc(Main.trkwtest)::Any
│       │   %6 = %5(%4, Main.trkwtest, Main.x)::Any
│       └──      return %6
│    )
└ @ Cassette ~/.julia/dev/Cassette/src/utilities.jl:131
┌ Debug: returning overdubbed CodeInfo
│   args = (getfield(Main, Symbol("##9#10")),)
│   body =
│    CodeInfo(
│    79 1 ─      :(#self# = (Core.getfield)(Core.Compiler.Argument(3), 1))
│       │   %2 = (:_y, :_z)::Any
│       │   %3 = Cassette.overdub(%%##recurse_context#376, Core.apply_type, Core.NamedTuple, %2)::Any
│       │   %4 = Cassette.overdub(%%##recurse_context#376, Core.tuple, Main.y, Main.z)::Any
│       │   %5 = Cassette.overdub(%%##recurse_context#376, %3, %4)::Any
│       │   %6 = Cassette.overdub(%%##recurse_context#376, Core.kwfunc, Main.trkwtest)::Any
│       │   %7 = Cassette.overdub(%%##recurse_context#376, %6, %5, Main.trkwtest, Main.x)::Any
│       └──      return %7
│    )
└ @ Cassette ~/.julia/dev/Cassette/src/utilities.jl:131
```
resulting in
```julia
@context TraceCtx
function Cassette.prehook(ctx::TraceCtx, f, args...)
    println((' ' for _ in 1:ctx.metadata[])..., f, args)
    ctx.metadata[] += 1
end
function Cassette.posthook(ctx::TraceCtx, f, args...)
    ctx.metadata[] -= 1
end
```
giving
```julia
julia> @overdub TraceCtx(metadata=Ref(0)) trkwtest(x, _y=y, _z=z)
Core.apply_type(NamedTuple, (:_y, :_z))
tuple(0.5089970904510814, 0.05603573446359866)
NamedTuple{(:_y, :_z),T} where T<:Tuple((0.5089970904510814, 0.05603573446359866),)
 typeof((0.5089970904510814, 0.05603573446359866),)
 Core.apply_type(NamedTuple, (:_y, :_z), Tuple{Float64,Float64})
 NamedTuple{(:_y, :_z),Tuple{Float64,Float64}}((0.5089970904510814, 0.05603573446359866),)
  Core.apply_type(NamedTuple, (:_y, :_z), Tuple{Float64,Float64})
  getfield((0.5089970904510814, 0.05603573446359866), 1)
  getfield((0.5089970904510814, 0.05603573446359866), 2)
Core.kwfunc(trkwtest,)
getfield(Main, Symbol("#kw##trkwtest"))()((_y = 0.5089970904510814, _z = 0.05603573446359866), trkwtest, 0.20226425240671442)
 #trkwtest#8(0.5089970904510814, 0.05603573446359866, trkwtest, 0.20226425240671442)
  trtest(0.20226425240671442, 0.5089970904510814, 0.05603573446359866)
   *(0.20226425240671442, 0.5089970904510814)
    mul_float(0.20226425240671442, 0.5089970904510814)
   *(0.5089970904510814, 0.05603573446359866)
    mul_float(0.5089970904510814, 0.05603573446359866)
   +(0.10295191597728079, 0.02852202580326111)
    add_float(0.10295191597728079, 0.02852202580326111)
```
Detecting (and avoiding recursing into) that code isn't too hard though (but maybe it'll be more annoying to make it inferrable). With this patch:
```patch
--- a/src/overdub.jl
+++ b/src/overdub.jl
@@ -67,6 +67,9 @@ end
 const RECURSE_CTX_SYMBOL = gensym("recurse_context")
 const RECURSE_ARGS_SYMBOL = gensym("recurse_arguments")
 
+@inline iskwfunccall(::Any) = false
+@inline iskwfunccall(x::Expr) = length(x.args) > 0 && x.args[1] == Base.GlobalRef(Core, :kwfunc)
+
 # The `recurse` pass has four intertwined tasks:
 #   1. Apply the user-provided pass, if one is given
 #   2. Munge the reflection-generated IR into a valid form for returning from
@@ -151,10 +154,14 @@ function recurse_pass!(reflection::Reflection,
     # assumptions are obviously quite fragile, so we should eventually get Base to expose
     # a standard/documented API for this.
     iskwfunc = startswith(String(signature.parameters[1].name.name), "#kw##")
+    kwfunccalls = iskwfunccall.(code_info.code)
+    nooverdubs = kwfunccalls .| (kwfunccalls << 1) .| (kwfunccalls << 2) .| (kwfunccalls << 3)
     for i in 1:length(code_info.code)
         stmnt = code_info.code[i]
         replaceable = Base.Meta.isexpr(stmnt, :foreigncall) ? view(stmnt.args, 2:length(stmnt.args)) : stmnt
-        replacement = iskwfunc && i !== (length(code_info.code)-1) ? :call : :overdub
+        nooverdub = iskwfunc && i !== (length(code_info.code)-1)
+        nooverdub = nooverdub || nooverdubs[i]
+        replacement = nooverdub ? :call : :overdub
         replace_match!(is_call, replaceable) do call
             call.args = Any[GlobalRef(Cassette, replacement), overdub_ctx_slot, call.args...]
             return call
```
we have
```julia
julia> @overdub TraceCtx(metadata=Ref(0)) trkwtest(x, _y=y, _z=z)
getfield(Main, Symbol("#kw##trkwtest"))()((_y = 0.8623782619990419, _z = 0.290266330284608), trkwtest, 0.5954523251552191)
 #trkwtest#6(0.8623782619990419, 0.290266330284608, trkwtest, 0.5954523251552191)
  trtest(0.5954523251552191, 0.8623782619990419, 0.290266330284608)
   *(0.5954523251552191, 0.8623782619990419)
    mul_float(0.5954523251552191, 0.8623782619990419)
   *(0.8623782619990419, 0.290266330284608)
    mul_float(0.8623782619990419, 0.290266330284608)
   +(0.5135051412706462, 0.2503193734276801)
    add_float(0.5135051412706462, 0.2503193734276801)
```
which is probably good enough—although it would be fantastic if Cassette never broke the kwargs abstraction at all, and gave something like
```julia
julia> @overdub TraceCtx(metadata=Ref(0)) trkwtest(x, _y=y, _z=z)
trkwtest(0.5954523251552191; _y=0.8623782619990419, _z=0.290266330284608)
 trtest(0.5954523251552191, 0.8623782619990419, 0.290266330284608)
  *(0.5954523251552191, 0.8623782619990419)
   mul_float(0.5954523251552191, 0.8623782619990419)
  *(0.8623782619990419, 0.290266330284608)
   mul_float(0.8623782619990419, 0.290266330284608)
  +(0.5135051412706462, 0.2503193734276801)
   add_float(0.5135051412706462, 0.2503193734276801)
```

**Comment by jekbradbury** [comment]
Hmm; even with that patch I'm not sure I have what I want—I guess I was hoping I could intercept kwargs calls using the overdubbing machinery, so a method like this:
```julia
function Cassette.execute(ctx::TraceCtx, ::typeof(Base.mapreduce), f, op,
                          A::AbstractArray; dims=:)
    @info f, op, size(A), dims
    return Base.mapreduce(f, op, A; dims=dims)
end
```
could intercept the kwargs call to `Base.mapreduce` that happens inside e.g. `sum(x, dims=1)`. But for some reason that method can currently intercept only non-kwargs calls to `Base.mapreduce`, not kwargs calls.

**Comment by jrevels** [comment]
Yeah, supporting kwargs in that way without wrecking performance is tricky - Julia's kwarg-splatting-related perf bugs seem even more plentiful than the normal splatting-related perf bugs. 

This might be more feasible after #63, though, since now Cassette is no longer callsite splatting overdubbed functions (woohoo!). The question is whether or not adding kwarg splatting to contextual method signatures will introduce more performance bugs/edge cases...

Let's reopen #48 and continue discussion there.

**Pull request merged**
