### PR TITLE
refactor overdub/context code

### PR DESCRIPTION
**Pull request by jrevels**
- keep caller with varargs while passing through overdub operations
- remove Overdub object, which only existed previously in order to work around unwanted type normalization
- the object formally known as TraceConfig is now the context struct itself, generated along with a context-specific tag type at context definition time
- change overdub macro to pass in context object to make box construction/destruction easier

@vtjnash This (along with https://github.com/JuliaLang/julia/pull/26826) renders the test case from #31 inferrable! (cc @maleadt)

```julia
julia> @code_warntype Cassette.overdub_execute(Ctx(), unsafe_load, pointer(Float32[]))
Variables:
  ctx<optimized out>
  args::Tuple{typeof(unsafe_load),Ptr{Float32}}
  i<optimized out>

Body:
  begin
      Core.SSAValue(15) = (Core.getfield)(args::Tuple{typeof(unsafe_load),Ptr{Float32}}, 2)::Ptr{Float32}
      Core.SSAValue(74) = (pointerref)(Core.SSAValue(15), 1, 1)::Float32
      return Core.SSAValue(74)
  end::Float32
```

~The intermediate `IntrinsicFunction` call doesn't "look" inferred, though. Why is that? It looks similar to `code_warntype` output we saw when testing the original `vararg_type_container` trick, which IIRC, was just due to the respecialization happening at a later stage. Is this just the same thing? Is it a problem at all?~ EDIT: We fixed the problem Jameson highlighted below, so I've updated the code snippet above (even the intermediate stuff is now inferred).

### CODE REVIEW

**Comment by jrevels** [comment]
@keno may also be happy to know that the above inference is possible without setting `aggressive_constant_propagation` to `true`.

**Comment by vtjnash** [comment]
> Why is that?

Most likely that means you’ve gotten the cache lookup algorithm wrong (failing to find the match)

**Comment by jrevels** [comment]
Note that this (along with JuliaLang/julia#26826) fixes #5

**Comment by jrevels** [comment]
The current thing that's keeping this branch from being useable:

```julia
julia> using Cassette: @context, @prehook, @overdub

julia> @context Ctx

julia> @prehook (f::Any)(args...) where {__CONTEXT__<:Ctx} = println(f, args)

julia> function foo(T)
           if isa(T, UnionAll)
               return UnionAll(T.var, foo(T.body))
           elseif isa(T, Union)
               return Union{foo(T.a), foo(T.b)}
           else
               return T
           end
       end
foo (generic function with 1 method)

julia> S = Tuple{Vararg{T}} where T
Tuple{Vararg{T,N} where N} where T

julia> foo(S)
Tuple{Vararg{T,N} where N} where T

julia> @overdub(Ctx(), foo(S))
foo(Tuple{Vararg{T,N} where N} where T,)
isa(Tuple{Vararg{T,N} where N} where T, UnionAll)
Base.getproperty(Tuple{Vararg{T,N} where N} where T, :var)
getfield(Tuple{Vararg{T,N} where N} where T, :var)
Base.getproperty(Tuple{Vararg{T,N} where N} where T, :body)
getfield(Tuple{Vararg{T,N} where N} where T, :body)
foo(Tuple{Vararg{T,N} where N},)
isa(Tuple{Vararg{T,N} where N}, UnionAll)
Base.getproperty(Tuple{Vararg{T,N} where N}, :var)
getfield(Tuple{Vararg{T,N} where N}, :var)
ERROR: type DataType has no field var
Stacktrace:
 [1] overdub_execute at /Users/jarrettrevels/.julia/v0.7/Cassette/src/overdub.jl:9 [inlined]
 [2] overdub_recurse at /Users/jarrettrevels/.julia/v0.7/Cassette/src/overdub.jl:155 [inlined]
 [3] overdub_execute at /Users/jarrettrevels/.julia/v0.7/Cassette/src/overdub.jl:34 [inlined]
 [4] overdub_recurse(::Ctx{Cassette.Unused,0x0000000000006ba0,Cassette.Unused,getfield(Main, Symbol("##CtxTag#1559")){Nothing,0xa96e611db2fca271}}, ::typeof(foo), ::Type{Tuple{Vararg{T,N} where N} where T}) at /Users/jarrettrevels/.julia/v0.7/Cassette/src/overdub.jl:3
 [5] overdub_execute at /Users/jarrettrevels/.julia/v0.7/Cassette/src/overdub.jl:34 [inlined]
 [6] overdub_recurse(::Ctx{Cassette.Unused,0x0000000000006ba0,Cassette.Unused,getfield(Main, Symbol("##CtxTag#1559")){Nothing,0xa96e611db2fca271}}, ::typeof(foo), ::Type{Tuple{Vararg{T,N} where N} where T}) at /Users/jarrettrevels/.julia/v0.7/Cassette/src/overdub.jl:3
 [7] overdub_execute at /Users/jarrettrevels/.julia/v0.7/Cassette/src/overdub.jl:34 [inlined]
 [8] overdub_recurse(::Ctx{Cassette.Unused,0x0000000000006ba0,Cassette.Unused,getfield(Main, Symbol("##CtxTag#1559")){Nothing,0xa96e611db2fca271}}, ::getfield(Main, Symbol("##4#5")), ::Ctx{Cassette.Unused,0x0000000000006ba0,Cassette.Unused,getfield(Main, Symbol("##CtxTag#1559")){Nothing,0xa96e611db2fca271}}) at /Users/jarrettrevels/.julia/v0.7/Cassette/src/overdub.jl:155
 [9] top-level scope at /Users/jarrettrevels/.julia/v0.7/Cassette/src/macros.jl:68
```

**Pull request merged**
