### PR TITLE
Switch from Travis/AV to GitHub Actions CI

### PR DESCRIPTION
**Pull request by DilumAluthge**
After this pull request is merged, a repository owner will need to do the following:
1. `using DocumenterTools; DocumenterTools.genkeys()`
2. Take the Base64-encoded private key and add it as a GitHub Secret (https://github.com/jrevels/Cassette.jl/settings/secrets/actions) named `DOCUMENTER_KEY`.
3. Take the public key and add it as a deploy key (https://github.com/jrevels/Cassette.jl/settings/keys) named `DOCUMENTER_KEY_PUBLIC`. Make sure that the deploy key has write access.

### CODE REVIEW

**Comment by DilumAluthge** [comment]
This is ready for review.

cc: @vchuravy

**Comment by DilumAluthge** [comment]
Bump @jrevels @vchuravy

**Comment by vchuravy** [comment]
Thanks DIlum!

**Comment by DilumAluthge** [comment]
FYI an admin needs to add the DOCUMENTER_KEY as described above, to ensure that the docs keep building.

**Comment by vchuravy** [comment]
That means we need @jrevels

**Pull request merged**
