### PR TITLE
Interface Stuff

### PR DESCRIPTION
**Pull request by MikeInnes**
The first commit adds the `@overdub` macro, like

```julia
@overdub Ctx 2+2
```

For most cases I've tried so far the current interface is unnecessary as we don't need any distinction between arguments and closed variables. This is much nicer for repl usage and showing examples of Cassette usage.

The second commit changes

```julia
@primitive Ctx (::typeof(+))(a, b) = ...
```

to

```julia
@primitive Ctx +(a, b) = ...
# or even
@primitive Ctx a + b = ...
```

I think it's more intuitive if this is as close to normal function definition as possible, just with a context. To get the (unusual) catch-all case you can still do

```julia
@primitive Ctx (f::Any)(args...) = ...
````

### CODE REVIEW

**Comment by jrevels** [comment]
LGTM. IIUC, this changes `@hook` and `@isprimitive` as well. Wanna update/add some tests (doesn't need to be comprehensive, Cassette testing is still pretty sparse at this point)?

**Comment by jrevels** [comment]
woah didn't even realize Cassette tests *could* pass on CI these days, I guess more recent v0.7-dev builds are available now

**Comment by MikeInnes** [comment]
Magic fingers – I even increased coverage, apparently!

**Comment by jrevels** [comment]
Would the following now be correct syntax after this change:

```julia
@primitive Ctx (f::Function)(args...) = # any <:Function
@primitive Ctx (f::Any)(args...) = # any other callable object
```

In general, this still allows the old

```julia
@primitive Ctx (name::typeof(something))(args...) = # ...
```

right?

Seems like the answers to both of these is "yes" but I just want to make sure

**Comment by MikeInnes** [comment]
Yeah that's correct. Anything with `::` we leave alone entirely. I'm not 100% sure that makes it identical to normal function definition, but I don't know of any other cases.

**Comment by jrevels** [comment]
Is there anything left to do here, or shall I merge?

**Comment by MikeInnes** [comment]
Please do

**Pull request merged**
