### PR TITLE
some inferability workarounds

### PR DESCRIPTION
**Pull request by jrevels**
needed for #53 

Not sure whether it merits opening an issue in Base Julia; I'm assuming the lack of specialization by default ([as mentioned here](https://github.com/jrevels/Cassette.jl/issues/53#issuecomment-405255104)) is an intentional barrier to overspecialization. @vtjnash Is this worth pursuing a  "fix" in the compiler?

### CODE REVIEW

**Comment by jrevels** [comment]
Argh. This performance workaround steers us back into the broken subtyping bug that we were working around before.

**Comment by jrevels** [comment]
Alright, restricted the specialized methods to `f::Core.Builtin`, which should prevent these methods from being applicable to functions which are affected by broken subtyping

**Comment by jrevels** [comment]
@Keno This PR now resolves #53 (these issues are good for perf debugging, thanks for opening them)

**Comment by Keno** [comment]
Thanks. #54 is the next one after this.

**Pull request merged**
